// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityOMS.API.Data;

#nullable disable

namespace UtilityOMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616080725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("UtilityOMS.API.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeadTechnician")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Crews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeadTechnician = "John Smith",
                            Name = "Alpha Team",
                            PhoneNumber = "555-1001",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            LeadTechnician = "Jane Doe",
                            Name = "Beta Team",
                            PhoneNumber = "555-1002",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            LeadTechnician = "Carlos Rivera",
                            Name = "Delta Team",
                            PhoneNumber = "555-1003",
                            Status = 3
                        });
                });

            modelBuilder.Entity("UtilityOMS.API.Models.Outage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AffectedCustomers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssigendCrewId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedCrewId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cause")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reportedby")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigendCrewId");

                    b.ToTable("Outages");
                });

            modelBuilder.Entity("UtilityOMS.API.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailOptIn")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("SmsOptIn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Email = "alice@example.com",
                            EmailOptIn = true,
                            Latitude = 40.712800000000001,
                            Longitude = -74.006,
                            Name = "Alice Johnson",
                            PhoneNumber = "555-2001",
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SmsOptIn = true
                        });
                });

            modelBuilder.Entity("UtilityOMS.API.Models.Outage", b =>
                {
                    b.HasOne("UtilityOMS.API.Models.Crew", "AssigendCrew")
                        .WithMany("Outages")
                        .HasForeignKey("AssigendCrewId");

                    b.Navigation("AssigendCrew");
                });

            modelBuilder.Entity("UtilityOMS.API.Models.Crew", b =>
                {
                    b.Navigation("Outages");
                });
#pragma warning restore 612, 618
        }
    }
}
